name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'apps/app1/**'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and Publish .NET app
      run: |
        cd apps/app1
        dotnet publish --configuration Release --output ./publish

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: |
        cd apps/app1
        docker build --tag app1 .

    - name: Increment Docker image tag
      id: increment
      run: |
        TAG=$(curl --silent https://registry.hub.docker.com/v2/repositories/${{ secrets.DOCKER_HUB_USERNAME }}/app1/tags/ | jq -r '[.results[].name] | map(select(test("^v\\d+\\.\\d+\\.\\d+$"))) | max // "v0.0.0"')
        MAJOR=$(echo "$TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1/')
        MINOR=$(echo "$TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\2/')
        PATCH=$(echo "$TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\3/')
        NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
        echo "New tag: $NEW_TAG"
        echo "TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Publish Docker image
      run: |
        docker tag app1 ${{ secrets.DOCKER_HUB_USERNAME }}/app1:${{ env.TAG }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/app1:${{ env.TAG }}
